### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by HugoGiraudel** [davidpollet/prescssk#1]
1\. A framework should be usable out-of-the-box, without triggering any compilation error. Things like this however are invalid Sass:

```sass
$color_1 : ;
```

Either set them to `null`, or a better approach would be to define a default palette (using `!default`) that the user can redefine if needed. That would also prevent [this kind of thing](https://github.com/davidpollet/prescssk/blob/master/sass/prescssk/_helpers.scss#L24-L27).

2\. Sass stylesheets should not be compressed and should always be printed in an expanded format. Some stylesheets such as the reset in _base.scss are barely readable. 

3\. Icons are defined [here](https://github.com/davidpollet/prescssk/blob/master/sass/prescssk/_library.scss#L35) but not used [there](https://github.com/davidpollet/prescssk/blob/master/sass/prescssk/_helpers.scss#L65). Why?

4\. [Some font names are quoted, some are not](https://github.com/davidpollet/prescssk/blob/master/sass/prescssk/_library.scss#L79). Either quote none of them or all of them.

5\. I'd argue you don't need 3 mixins for background related stuff but that's really my own opinion at this point.

6\.`visible` mixin only cancels some part of `invisible`. Also, it usually is considered bad practice to undo styles. 

7\. You wouldn't need a `visible_custom` mixin if the visible mixin was written like this:

```scss
@mixin visible($width: auto, $height: auto, $margin: auto, $clip:auto) {
  width: $width;
  height: $height;
  margin: $margin;
  clip : $clip;
}
```

Then it can be used with or without arguments, as they all have sensible defaults. By the way, note that I re-ordered arguments to make more sense.

8\. The `$base-font-size` variable should not be defined [here](https://github.com/davidpollet/prescssk/blob/master/sass/prescssk/_mixins.scss#L96).

9\. I'd argue you don't need to take care of IE6 and 7 anymore: https://github.com/davidpollet/prescssk/blob/master/sass/prescssk/_mixins.scss#L113 and https://github.com/davidpollet/prescssk/blob/master/sass/prescssk/_mixins.scss#L216.

10\. You define `$fw` and `$fs` arguments in your font-face mixins but you do not use them.

11\. The unit handling in your `rem-*` mixins is pretty bad. Same for all your media-query mixins. Check http://www.sitepoint.com/understanding-sass-units/.

12\. `rem-maw` relies on a global `$max_height` variable which is bad practice, and you do nothing with the given `$value` argument. Same for `rem-mah`.

13\. Your grid system uses a lot of magic numbers. The point of Sass and its ability to perform computation before hitting the browser is to abstract the complexity and avoid any magic number on the author environment.

14\. All in all, I feel like it is quite obscure at the moment, especially in regard to the naming in use. Sometimes it uses underscores, sometimes not. I'd recommend using hyphens only as CSS is heavily hyphenated. More importantly, I feel like you should name your variables and mixins in a much more friendly way and avoid hard-to-grasp shortcuts.

Hope it helps. Cheers! :)

**Comment by davidpollet** [comment]
Salut Hugo,
https://www.youtube.com/watch?v=yUbifff0BIw :p

1 - C'est noté. Dans les faits, il y a toujours 1 voir 2 couleurs à stocker. C'est la raison pour laquelle j'ai rien mit plutôt que "null". 
2 - Ok.
3 - Copié / collé / Control + F. ;)
4 - Je n'y ai jamais songé comme ça fonctionne comme ça.
5 - Le plus utile selon moi est le bg_tinted. Les deux autres le sont un peu moins mais peuvent dépaner. Après, je fais beaucoup
6 - Tu as quelque chose de mieux à proposer pour qu'un rendre visible un élement invisible ? Une média queries à deux valeurs peut être. Oui, je réponds à mes propres questions. 8)
7 & 8 - o-k
9 - Je pense que si. Du moins pendant encore un petit moment. Ca ne demande pas d'effort supplémentaire de le faire et ça ne fait pas démesurement gonfler ta css.
10 - Oups. Oublie. J'ai remis à jour ce mixin pour ajouter un paramètre de support mais j'ai omis ces deux variables.
11 - J'ai mis ton article dans pocket et ferait les modfis si il y a lieu.
12 - Encore un oublie.
13 - Je vois pas ce que tu veux dire. J'ai 'traduit' en % ces grilles : http://gridulator.com/ (1140 px | 12 col). On a 5 grilles selon la taille des goutières que l'on veut. Une grille responsive est forcement faite avec des nombres magiques non ?
14 - Tu trouves vraiment difficile à lire ? Même en sachant que c'est strictement basé sur Emmet ?

Merci beaucoup pour le temps que tu m'as accordé. Je vais prendre en compte tes remarques.
T'as trouvé des choses intéréssantes ou pas du tout au final ? Je suis tenté de dire non. :d

**Comment by HugoGiraudel** [comment]
9\. J'imagine que ça dépend des projets. J'entends bien la remarque cela dit.
11\. Il y a lieu. ;)
13\. Je ne suis pas d'accord. Ces nombres sortent bien de quelque part, ils sont vraisemblablement le résultat d'un calcul. Ce calcul devrait être délégué à Sass plutôt que d'être fait hors de la feuille de styles.
14\. Je trouve difficile à lire oui. Les styles sur une seule ligne, le manque de cohérence générale, tout ça fait que c'est pas une feuille de styles que je trouve agréable à lire en ce qui me concerne.

Je n'ai pas vraiment regardé le fond je dois avouer, surtout la forme. :)

**Comment by davidpollet** [comment]
11. J'en doute pas. ^^ Je me garde une -petite - marge de doute tant que je ne me suis pas fait ma propre opinion.
13. Je comprends mieux. La conversion px --> % a été faite sur papier, loin d'un PC. Mais quelqu'un qui lit le code doit se demander d'où débarque ces chiffres sortis - à priori - de nullpart.
14. Je voulais surtout parler du choix de la syntaxe emmet, qui part d'une reflexion perso sur un moyen d'avoir une syntaxe très courte mais comprise par le plus grand nombre. Le reste sont des erreurs d'innatentions ou un mauvais choix qui se corrige facilement.

**Comment by davidpollet** [comment]
Salut Hugo,
J'ai mis à jour. J'espère que l'on comprends mieux d'où sortent les chiffres mon mixin "grille" désormais.
